export const RoleMappings: any = {
  SUPERADMIN: 'SUPERADMIN',
  CREATE_USER: 'R_GEN_USER_001',
  FETCH_USERS_BY_FILTER: 'R_GEN_USER_002',

  FETCH_INCOMING_REQUEST_TYPE: 'R_GEN_INCOMING_REQUEST_001',

  FETCH_AIRTEL_TRANSACTIONS: 'R_AIRTEL_GET_MULTIPLE',
  FETCH_HALOTEL_TRANSACTIONS: 'R_HALOTEL_GET_MULTIPLE',
  FETCH_TIGO_TRANSACTIONS: 'R_TIGO_GET_MULTIPLE',
  FETCH_VODACOM_TRANSACTIONS: 'R_VODACOM_GET_MULTIPLE',
  FETCH_ZANTEL_TRANSACTIONS: 'R_ZANTEL_GET_MULTIPLE',
};
