CREATE TABLE `api_configurations` (
  `api_configuration_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `path` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL,
  `request_type` ENUM('object', 'string', 'form') COLLATE utf8mb4_bin NOT NULL COMMENT 'This is the type of the request for parsing',
  `request` text,
  `request_options` text,
  `error_response` text,
  `success_response` text,
  `response_options` text,
  `skip_validation` tinyint(1) DEFAULT '0',
  `type` ENUM('incoming', 'outgoing') COLLATE utf8mb4_bin DEFAULT NULL,
  `status` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`api_configuration_id`)
) ENGINE=InnoDB DEFAULT AUTO_INCREMENT=1 CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO api_configurations (`path`,`request_type`,`request`,`request_options`,`response_options`,`type`, `skip_validation`,`status`) VALUES
('/explorer','string','',NULL,NULL,'incoming', '1','active'),
('/explorer/openapi.json','string','',NULL,NULL,'incoming', '1','active'),
('/explorer/','string','',NULL,NULL,'incoming', '1','active'),
('/favicon.ico','string','',NULL,NULL,'incoming', '1','active');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/Airtel/airtelTransactions/UssdPush/Callback','string',NULL,NULL,'incoming','active', '`{"COMMAND": {"APIusername": "string","APIPassword": "string","transID": "string","amount": "string","paybillnumber": "string","referenceField": "string","MSISDN": "string"}}`'),
('AirtelTransactionSuccessResponse','string','{ "URL": "http://mq.azammedia.com/mqsapiws/Service.asmx", "METHOD": "POST", "HEADERS": {"Content-type": "text/xml"} }',NULL,'outgoing','active', '`<?xml version="1.0" encoding="UTF - 8"?><COMMAND><TYPE>${options.TYPE ? options.TYPE : "failure"}</TYPE><TXNSTATUS>${options.TXNSTATUS ? options.TXNSTATUS : 500}</TXNSTATUS><MESSAGE>${options.MESSAGE ? options.MESSAGE : "Internal server error"}</MESSAGE></COMMAND>`'),
('AirtelTransactionErrorResponse','string','{ "URL": "http://mq.azammedia.com/mqsapiws/Service.asmx", "METHOD": "POST", "HEADERS": {"Content-type": "text/xml"} }',NULL,'outgoing','active', '`<?xml version="1.0" encoding="UTF - 8"?><COMMAND><TYPE>${options?.TYPE ? options.TYPE : "failure"}</TYPE><TXNSTATUS>${options?.TXNSTATUS ? options.TXNSTATUS : 500}</TXNSTATUS><MESSAGE>${options?.MESSAGE ? options.MESSAGE : "Internal server error"}</MESSAGE></COMMAND>`'),
('/Airtel/airtelTransactionsNormalUssd','string','{"replacement_fields": {"COMMAND": "RequestToken", "transID": "TransID", "amount": "Amount", "referenceField": "ReferenceField", "MSISDN": "Msisdn", "paybillnumber": "utilitycode"}}',NULL,'incoming','active', '`<COMMAND><APIusername>string</APIusername><APIPassword>string</APIPassword><transID>string</transID><amount>string</amount><paybillnumber>string</paybillnumber><referenceField>string</referenceField><MSISDN>string</MSISDN></COMMAND>`'),
('/airtelTransactionsNormalUssd','string','{"replacement_fields": {"COMMAND": "RequestToken", "transID": "TransID", "amount": "Amount", "referenceField": "ReferenceField", "MSISDN": "Msisdn", "paybillnumber": "utilitycode"}}',NULL,'incoming','active', '`<COMMAND><APIusername>string</APIusername><APIPassword>string</APIPassword><transID>string</transID><amount>string</amount><paybillnumber>string</paybillnumber><referenceField>string</referenceField><MSISDN>string</MSISDN></COMMAND>`'),
('/airtelTransactions/UssdPush/Callback','string',NULL,NULL,'incoming','active', '`{"COMMAND": {"APIusername": "string","APIPassword": "string","transID": "string","amount": "string","paybillnumber": "string","referenceField": "string","MSISDN": "string"}}`'),
('ValidateAccountTest','object','{ "URL": "http://localhost:8080/ValidateAccount", "METHOD": "POST", "HEADERS": { "Content-type": "text/xml" } }',NULL,'outgoing','active', '`{ "SOURCE": "${options.integrationPartner.SOURCE}", "XREF": "${options.integrationPartner.XREF}", "USER_ID": "${options.integrationPartner.USER_ID}", "PASSWORD": "${options.integrationPartner.PASSWORD}", "SERVICE": "DSBAccountService", "OPERATION": "ValidateAccount"}`'),
('ValidateAccount','string','{ "URL": "http://localhost:8080/ValidateAccount", "METHOD": "POST", "HEADERS": { "Content-type": "text/xml" } }',NULL,'outgoing','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"xmlns:acc="http://dsbflex.dtbafrica.com/accountservice/DSBAccountService/AccountValidation/"><soapenv:Header /><soapenv:Body><acc:DSB_VALACCOUNT_REQ><acc:DSB_HEADER><acc:SOURCE>${options.paymentPartner.SOURCE}</acc:SOURCE><acc:XREF>${options.paymentPartner.XREF}</acc:XREF><acc:USER_ID>${options.paymentPartner.USER_ID}</acc:USER_ID><acc:PASSWORD>${options.paymentPartner.PASSWORD}</acc:PASSWORD><acc:SERVICE>DSBAccountService</acc:SERVICE><acc:OPERATION>ValidateAccount</acc:OPERATION></acc:DSB_HEADER><acc:DSB_BODY><acc:ACCOUNT_REQUEST_DETAIL><acc:ACCOUNT_NUMBER>${options.userDetails.ACCOUNT_NUMBER}</acc:ACCOUNT_NUMBER></acc:ACCOUNT_REQUEST_DETAIL></acc:DSB_BODY></acc:DSB_VALACCOUNT_REQ></soapenv:Body></soapenv:Envelope>`'),

('/azam/airtel/ussdnormal','string','{"replacement_fields": {"COMMAND": "RequestToken", "transID": "TransID", "amount": "Amount", "referenceField": "ReferenceField", "MSISDN": "Msisdn", "paybillnumber": "utilitycode"}}',NULL,'incoming','active', '`<COMMAND><APIusername>string</APIusername><APIPassword>string</APIPassword><transID>string</transID><amount>string</amount><paybillnumber>string</paybillnumber><referenceField>string</referenceField><MSISDN>string</MSISDN></COMMAND>`'),
('/azam/airtel/ussdpush','object',NULL,NULL,'incoming','active', '{"PartnerCode": "string", "CustomerMsisdn": "string", "Amount": "string", "ReferenceMsisdn": "string"}'),
('/azam/airtel/ussdpush/callback','string',NULL,NULL,'incoming','active', '`{"COMMAND": {"APIusername": "string","APIPassword": "string","transID": "string","amount": "string","paybillnumber": "string","referenceField": "string","MSISDN": "string"}}`');

INSERT INTO api_configurations(`path`, `request_type`, `request_options`, `type`, `skip_validation`, `status`, `request`) VALUES
('InfobipPath', 'object', '{ "URL": "http://pz6pm.api.infobip.com/sms/1/text/single","HEADERS": { "Content-Type": "application/json", "Authorization": "App 78a500a60f2f605e30f7e4f4c6027823-70a938d2-a288-4172-ba79-53a8995e05f4" }, "AUTH_TOKEN": "App 78a500a60f2f605e30f7e4f4c6027823-70a938d2-a288-4172-ba79-53a8995e05f4","METHOD": "POST","CONTENT_TYPE": "application/json","JSON": true }', 'outgoing', 1, 'active', '`{"from": "AZMA GATEWAY", "to": ${options.MobileNumber} || "+917760225405", "text": ${options.SmsText} || "Is a dummy otpcode"}`');

INSERT INTO api_configurations (`path`, `request_type`, `request_options`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`, `request`) VALUES
('CheckUserForAzamTVRequest','string','{"URL": "https://testmq.azammedia.com/TestWebServices/Service.asmx","METHOD": "POST","HEADERS": {"Content-type": "text/xml"},"QS": {"WSDL": ""}, "REJECT_UNAUTHORIZED": false, "INSECURE": false}',NULL,0,'outgoing','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><Header><ns1:MQUserNameToken><ns1:User_id>AzamPay</ns1:User_id><ns1:Password>AzamPaytest20</ns1:Password><ns1:ExternalPartyName>AzamPay</ns1:ExternalPartyName></ns1:MQUserNameToken></Header><Body><ns1:GetCustomerInfo><ns1:CustomerInfoXML><![CDATA[<REQUESTINFO><KEY_NAMEVALUE><KEY_NAME>SMARTCARD</KEY_NAME><KEY_VALUE>${options.referenceNumber.senderMsisdn}</KEY_VALUE></KEY_NAMEVALUE></REQUESTINFO>]]></ns1:CustomerInfoXML><ns1:ReferenceNo>${options.referenceNo}</ns1:ReferenceNo></ns1:GetCustomerInfo></Body></Envelope>`'),
('PaymentMqService','string','{"URL": "https://testmq.azammedia.com/TestWebServices/Service.asmx","METHOD": "POST","HEADERS": {"Content-type": "text/xml"},"QS": {"WSDL": ""}, "REJECT_UNAUTHORIZED": false, "INSECURE": false}',NULL,0,'outgoing','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"> <Header><ns1:MQUserNameToken> <ns1:User_id>AzamPay</ns1:User_id> <ns1:Password>AzamPaytest20</ns1:Password><ns1:ExternalPartyName>AzamPay</ns1:ExternalPartyName> </ns1:MQUserNameToken> </Header><Body> <ns1:MakePayment> <ns1:MakePaymentXML><![CDATA[<REQUESTINFO><KEY_NAMEVALUE><KEY_NAME>SMARTCARD</KEY_NAME><KEY_VALUE>${options.smartCardNo}</KEY_VALUE></KEY_NAMEVALUE><PAYMENTINFO><AMOUNT>${options.amount}</AMOUNT><PAYMODE>CA</PAYMODE><RECEIPTNO>${options.reciptNo}</RECEIPTNO><PAYMENTDATE>${options.paymentDate}</PAYMENTDATE><OPENITEM>DEFAULT</OPENITEM><REMARKS>${options.remarks}</REMARKS></PAYMENTINFO></REQUESTINFO>]]></ns1:MakePaymentXML> <ns1:ReferenceNo>${options.referenceNo}</ns1:ReferenceNo> </ns1:MakePayment></Body></Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('validateTigoToken','form','{ "URL": "http://accessgwtest.tigo.co.tz:8080/AZAMPAY2DM-GetToken", "METHOD": "POST", "HEADERS": { "Content-type": "application/x-www-form-urlencoded" } }',NULL,'outgoing','active', '`{"username": "${options.Username}", "password": "${options.Password}", "grant_type": "password"}`'),
('/azam/tigo/validatetoken','object','{}',NULL,'incoming','active', '`{"Username": "string", "Password": "string"}`'),
('InitiateTigoTransaction','object','{ "URL": "http://accessgwtest.tigo.co.tz:8080/AZAMPAY2DM-PushBillpay", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"CustomerMSISDN": "${options.CustomerMSISDN}", "BillerMSISDN": "${options.BillerMSISDN}", "Amount": "${options.Amount}", "Remarks": "${options.Remarks}", "ReferenceID": "${options.ReferenceID}"}`'),
('/azam/tigo/initiatetransaction','object','{}',NULL,'incoming','active', '`{"CustomerMSISDN": "string", "ReferenceMSISDN": "string", "Amount": "string"}`'),
('QueryTigoTransaction','object','{ "URL": "https://10.222.130.104:9101/API/Heartbeat/Heartbeat", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"ReferenceID": "${options.ReferenceID}"}`'),
('/azam/tigo/querytransaction','object','{}',NULL,'incoming','active', '`{"ReferenceID": "string"}`'),
('PayTigoBillInSync','string','{ "URL": "https://10.222.130.104:9101/API/Heartbeat/Heartbeat", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`<?xml version="1.0"?><COMMAND><TYPE>string</TYPE><TXNID>string</TXNID><MSISDN>string</MSISDN><AMOUNT>string</AMOUNT><COMPANYNAME>string</COMPANYNAME><CUSTOMERREFERENCEID>string</CUSTOMERREFERENCEID></COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/tigo/ussdpush/callback','object',NULL,'`{"ResponseCode": "BILLER-18-3020-E", "ResponseStatus": false, "ResponseDescription": "Callback failed", "ReferenceID": "${options.ReferenceID}", "statusCode": 500}`', '`{"ResponseCode": "BILLER-18-0000-S", "ResponseStatus": true, "ResponseDescription": "Callback successful", "ReferenceID": "${options.ReferenceID}", "statusCode": 200}`',NULL,'incoming','active', '`{"Description": "string", "ReferenceID": "string", "Amount": "string"}`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('AirtelCallbackApi', 'string', '{"URL": "https://172.27.34.27:10031/?LOGIN=PushAPI&PASSWORD=MPtc1ToayCkCMZZeHUu0snA3a&REQUEST_GATEWAY_CODE=THIRDPARTY&REQUEST_GATEWAY_TYPE=USSD&requestText=","METHOD": "POST","HEADERS": {"Content-type": "application/xml"}}', null, null, 'outgoing', 'active', '`<COMMAND><TYPE>PUSHREQ</TYPE><MSISDN>${options.CustomerMsisdn}</MSISDN><MSISDN2>${options.MSISDN2}</MSISDN2><AMOUNT>${options.Amount}</AMOUNT><INTERFACEID>ONLINEPAY_${options.MSISDN2}</INTERFACEID><REFERENCE_NO>${options.ReferenceID}</REFERENCE_NO><EXT_TRID>${options.ExternalReferenceID}</EXT_TRID></COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/airtelTransactions/UssdPush/Callback','string','{"replacement_fields": {"COMMAND": "Command","EXTTRID": "ExternalReferenceID"}}',NULL,'incoming','active', '`<COMMAND><TYPE>CALLBCKREQ</TYPE><serviceType>CALLBCKREQ</serviceType><interfaceId>ONLINEPAY_{3ppname}</interfaceId><TXNSTATUS>200</TXNSTATUS><TXNID>MP180907.1925.B00001</TXNID><MESSAGE>success</MESSAGE><EXTTRID>1807111203222</EXTTRID><REFERENCE>null</REFERENCE><INTERFACEID>ONLINEPAY_{3ppname}</INTERFACEID></COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/halotel/ussd/validatePayment','string',NULL, '{"replacement_fields": {"soapenv:": "","int:": ""}}', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>${options.msg}</message><refid>${options.reference_id}</refid><response_time>${options.response_time}</response_time><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>${options.msg}</message><refid>${options.reference_id}</refid><response_time>${options.response_time}</response_time><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`','incoming','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://service.com/"><soapenv:Header /><soapenv:Body><int:HaloPesaServiceAPI><requestid>154329405</requestid><username>xxx</username><password>xxx</password><request_time>20180601092349</request_time><amount>1000</amount><sender_msisdn>255623333666</sender_msisdn><sender_name>NGUYEN HUU HANH</sender_name><referenceid>66952</referenceid><business_no></business_no><addition_data></addition_data><check_sum>b875460229adc88cef4bd9904b0b06748e2b2b10eb560078a7f0ace2ba4b2cb4</check_sum></int:HaloPesaServiceAPI></soapenv:Body></soapenv:Envelope>`');

UPDATE api_configurations SET request = '`<COMMAND><TYPE>PUSHREQ</TYPE><MSISDN>${options.CustomerMsisdn}</MSISDN><MSISDN2>${options.MSISDN2}</MSISDN2><AMOUNT>${options.Amount}</AMOUNT><INTERFACEID>ONLINEPAY_${options.InterfaceName}</INTERFACEID><REFERENCE_NO>${options.ReferenceID}</REFERENCE_NO><EXT_TRID>${options.ExternalReferenceID}</EXT_TRID></COMMAND>`',
request_options = '{ "URL": "https://172.27.34.27:10031/?LOGIN=PushAPI&PASSWORD=MPtc1ToayCkCMZZeHUu0snA3a&REQUEST_GATEWAY_CODE=THIRDPARTY&REQUEST_GATEWAY_TYPE=USSD&requestText=", "METHOD": "POST", "HEADERS": { "Content-type": "application/xml" }, "REJECT_UNAUTHORIZED": false, "AGENT_OPTIONS": { "securityOptions": "TLSv1_method", "CERT": "/home/atharv/Airtel_push_api.crt", "KEY": "/home/atharv/Airtel_push_api.key", "PASS_PHRASE": "PUSH_API@123" } }'
WHERE api_configurations.path = 'AirtelCallbackApi'
AND status = 'active';

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/vodacom/ussd/paymentIntimation','string', '{ "replacement_fields": {"spId": "CollectionAccountNumber", "spPassword": "CollectionAccountPassword"} }', null, '`<?xml  version="1.0" encoding="UTF-8"?><mpesaBroker xmlns="http://inforwise.co.tz/broker/" version="2.0"><response><conversationID>${options.request.transaction.conversationID}</conversationID><originatorConversationID>${options.request.transaction.originatorConversationID}</originatorConversationID><transactionID>${options.request.transaction.transactionID}</transactionID><responseCode>0</responseCode><responseDesc>Received</responseDesc><serviceStatus>Success</serviceStatus></response></mpesaBroker>`', '`<?xml  version="1.0" encoding="UTF-8"?><mpesaBroker xmlns="http://inforwise.co.tz/broker/" version="2.0"><response><conversationID>${options.request.transaction.conversationID}</conversationID><originatorConversationID>${options.request.transaction.originatorConversationID}</originatorConversationID><transactionID>${options.request.transaction.transactionID}</transactionID><responseCode>0</responseCode><responseDesc>Received</responseDesc><serviceStatus>Success</serviceStatus></response></mpesaBroker>`','incoming','active', '`<?xml version="1.0" encoding="UTF-8"?><mpesaBroker xmlns="http://infowise.co.tz/broker/" version="2.0"><request><serviceProvider><spId>string</spId><spPassword>string</spPassword><timestamp>string</timestamp></serviceProvider><transaction><amount>string</amount><commandID>string</commandID><initiator>string</initiator><originatorConversationID>string</originatorConversationID><recipent>string</recipent><mpesaRecipt>string</mpesaRecipt><transactionDate>string</transactionDate><accountReference>string</accountReference><transactionID>string</transactionID><conversationID>string</conversationID></transaction></request></mpesaBroker>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('VodacomResponseIntimation', 'string', '{"URL": "https://41.217.203.61:30009/iPG/c2b/multione","METHOD": "POST", "QS": { "WSDL": "" }, "HEADERS": { "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "Content-type": "text/xml" }}', null, null, 'outgoing', 'active', '`<mpesaBroker xmlns="http://inforwise.co.tz/broker/" version="2.0"><request><serviceProvider><spId>${options.spId}</spId><spPassword>${options.spPassword}</spPassword><timestamp>${options.timestamp}</timestamp></serviceProvider><transaction><resultType>${options.resultType}</resultType><resultCode>${options.resultCode}</resultCode><resultDesc>${options.resultDesc}</resultDesc><serviceReceipt>${options.serviceReceipt}</serviceReceipt><serviceDate>${options.serviceDate}</serviceDate><originatorConversationID>${options.originatorConversationID}</originatorConversationID><conversationID>${options.conversationID}</conversationID><transactionID>${options.transactionID}</transactionID><initiator>${options.initiator}</initiator><initiatorPassword>${options.initiatorPassword}</initiatorPassword></transaction></request></mpesaBroker>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/ussdpush/initiatepayment','object',NULL,NULL, null, null,'incoming','active', '`{ "PartnerCode": "string", "SenderMsisdn": "string", "ReferenceMsisdn": "string" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/halotel/ussdpush/updatepayment','string', '{ "replacement_fields": { "referenceid": "ReferenceID", "S:": "", "ns2:": "" } }', null, '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>Internal server error</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>Payment received</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', 'incoming','active', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>string</message><referenceid>string</referenceid><response_time>string</response_time><response_type>string</response_type><addition_data>string</addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/ext/halopesa/gp/callback','string', '{ "replacement_fields": { "referenceid": "ReferenceID", "S:": "", "ns2:": "" } }', null, '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>Internal server error</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>Payment received</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', 'incoming','active', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>string</message><referenceid>string</referenceid><response_time>string</response_time><response_type>string</response_type><addition_data>string</addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/ussdpush/callback','string', '{ "replacement_fields": { "referenceid": "ReferenceID", "S:": "", "ns2:": "" } }', null, '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>Internal server error</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>Payment received</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', 'incoming','active', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>string</message><referenceid>string</referenceid><response_time>string</response_time><response_type>string</response_type><addition_data>string</addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('PayHalotelInstance','string','{ "URL": "http://10.225.199.107:8018/ServiceAPI", "METHOD": "POST", "HEADERS": { "Content-type": "text/xml", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" } }', null, null, null,'outgoing','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.merchant.vmoney.viettel.com/"> <soapenv:Header /> <soapenv:Body> <ws:HaloPesaServiceAPI> <request> <requestid>${options.requestid}</requestid> <username>${options.username}</username> <password>${options.password}</password> <request_time>${options.request_time}</request_time> <amount>${options.amount}</amount> <sender_msisdn>${options.senderMsisdn}</sender_msisdn> <beneficiary_accountid>${options.beneficiary_accountid}</beneficiary_accountid> <referenceid>${options.referenceid}</referenceid> <business_no>${options.business_no}</business_no> <function_code>${options.function_code}</function_code> <addition_data /> <check_sum>${options.check_sum}</check_sum> </request> </ws:HaloPesaServiceAPI> </soapenv:Body></soapenv:Envelope>`');

UPDATE api_configurations set
`request` = '`<mpesaBroker xmlns="http://inforwise.co.tz/broker/" version="2.0"><result><serviceProvider><spId>${options.spId}</spId><spPassword>${options.spPassword}</spPassword><timestamp>${options.timestamp}</timestamp></serviceProvider><transaction><resultType>${options.resultType}</resultType><resultCode>${options.resultCode}</resultCode><resultDesc>${options.resultDesc}</resultDesc><serviceReceipt>${options.serviceReceipt}</serviceReceipt><serviceDate>${options.serviceDate}</serviceDate><originatorConversationID>${options.originatorConversationID}</originatorConversationID><conversationID>${options.conversationID}</conversationID><transactionID>${options.transactionID}</transactionID><initiator>${options.initiator}</initiator><initiatorPassword>${options.initiatorPassword}</initiatorPassword></transaction></result></mpesaBroker>`'
WHERE `path` = 'VodacomResponseIntimation';

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/zantel/ussd/normalTransaction','string', '{ "replacement_fields": { "SENDER": "senderMsisdn", "AMOUNT": "Amount", "PAYMENTCODE": "PaymentCode" } }', null, '`<RESPONSE> <REQUESTID>${options.REQUESTID}</REQUESTID> <REFERENCEID>${options.ReferenceID}</REFERENCEID> <TYPE>PAYMENT_RESPONSE</TYPE> <RESPONSETIME>${options.REQUESTTIME}</RESPONSETIME> <ERRORCODE>1</ERRORCODE> <ERRORDESC>Internal server error</ERRORDESC> <ADDDATA></ADDDATA> </RESPONSE>`', '``', 'incoming','active', '`<REQUEST><USERNAME>string</USERNAME><PASSWORD>string</PASSWORD><TYPE>string</TYPE><REQUESTTIME>string</REQUESTTIME><PAYMENTCODE>string</PAYMENTCODE><CUSTNAME>string</CUSTNAME><REQUESTID>string</REQUESTID><SENDER>string</SENDER><AMOUNT>string</AMOUNT><ADDDATA>string</ADDDATA><CHECKSUM>string</CHECKSUM></REQUEST>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('ZantelUssdPushService','string','{ "REJECT_UNAUTHORIZED": false, "URL": "https://41.204.152.247:443/3PPMRORUSSDPushService?wsdl", "QS": { "WSDL": "" }, "METHOD": "POST", "HEADERS": { "Content-type": "text/xml", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" } }', null, null, null,'outgoing','active', "`<soapenv:Envelope xmlns:soapenv=\'http://schemas.xmlsoap.org/soap/envelope/' xmlns:api='http://api.push.mror.zantel.tz.psi.com/'> <soapenv:Header /> <soapenv:Body> <api:PushRequest> <Credential> <Username>${options.Username}</Username> <Password>${options.Password}</Password> </Credential> <msisdn>${options.Msisdn}</msisdn> <referencedata1>${options.ReferenceData1}</referencedata1> <referencedata2>${options.ReferenceData2}</referencedata2> <amount>${options.Amount}</amount> </api:PushRequest> </soapenv:Body> </soapenv:Envelope>`");

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('ZantelQueryTransaction','string','{ "URL": "https:// 41.204.152.247:443/3PPMRORUSSDPushCheckTxn", "QS": { "WSDL": "" }, "METHOD": "POST", "HEADERS": { "Content-type": "text/xml", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" } }', null, null, null,'outgoing','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:api="http://api.push.mror.zantel.tz.psi.com/"> <soapenv:Header /> <soapenv:Body> <api:TransactionCheckRequest> <Credential> <Username>${options.Username}</Username> <Password>${options.Password}</Password> </Credential> <PushReferenceId>${options.PushReferenceId}</PushReferenceId> </api:TransactionCheckRequest> </soapenv:Body> </soapenv:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/crdb/verifymerchant','object', null, null, null, null,'incoming','active', '`{ "MerchantDetails": {} }`'),
('/azam/crdb/initiatetransaction','object', null, null, null, null,'incoming','active', '`{ "TransactionDetails": {} }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('CrdbMerchantVerification','object','{ "URL": "http://192.168.151.71:807/merchantuat/api/service/mip", "METHOD": "POST", "HEADERS": { "Content-type": "application/json", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" }, "JSON": true }', null, null, null,'outgoing','active', '`{ "code": "${options.code}", "customerName": "${options.customerName}", "customerAccount": "${options.customerAccount}", "customerMobile": "${options.customerMobile}", "otp": "${options.otp}", "merchantID": "${options.merchantID}", "token": "${options.token}", "checksum": "${options.checksum}" }`'),
('CrdbTransactionInitiation','object','{ "URL": "http://192.168.151.71:807/merchantuat/api/service/mip", "METHOD": "POST", "HEADERS": { "Content-type": "application/json", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" }, "JSON": true }', null, null, null,'outgoing','active', '`{ "code": "${options.code}", "paymentType": "${options.paymentType}", "paymentDesc": "${options.paymentDesc}", "merchantID": "${options.merchantID}", "customerToken": "${options.customerToken}", "amount": "${options.amount}", "currency": "${options.currency}", "paymentReference": "${options.paymentReference}", "token": "${options.token}", "checksum": "${options.checksum}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('AirtelUssdPush','object','{ "URL": "https://172.16.100.5:4301/azam/airtel/ussdpush", "METHOD": "POST", "REJECT_UNAUTHORIZED": false, "AGENT_OPTIONS": { "securityOptions": "TLSv1_method", "CERT": "/home/atharv/Airtel_push_api.crt", "KEY": "/home/atharv/Airtel_push_api.key", "PASS_PHRASE": "PUSH_API@123" } }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "CustomerMsisdn": "${options.CustomerMsisdn}", "ReferenceMsisdn": "${options.ReferenceMsisdn}", "Amount": "${options.Amount}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ValidateTigoTokenInternal','object','{ "URL": "https://172.16.100.5:4101/tigo/ValidateToken", "REJECT_UNAUTHORIZED": false, "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"Username": "${options.Username}", "Password": "${options.Password}"}`'),
('InitiateTigoTransactionInternal','object','{ "URL": "https://172.16.100.5:4101/tigo/InitiateTransaction", "REJECT_UNAUTHORIZED": false, "METHOD": "POST" }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "CustomerMSISDN": "${options.CustomerMSISDN}", "ReferenceMSISDN": "${options.ReferenceMSISDN}", "Amount": "${options.Amount}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('HalotelUssdPush','object','{ "URL": "https://172.16.111.5:4201/azam/halotel/ussdpush/initiatepayment", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "SenderMsisdn": "${options.SenderMsisdn}", "ReferenceMsisdn": "${options.ReferenceMsisdn}", "Amount": "${options.Amount}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ConfirmSarafuPayment','object','{ "URL": "http://3.120.252.221:4000/confirmPayment", "METHOD": "POST", "JSON": true }',NULL,'outgoing','active', '`{ "transactionstatus": "${options.TransactionStatus}", "message": "${options.Message}", "operator": "${options.Operator}", "reference": "${options.ReferenceID}", "utilityref": "${options.UtilityReference}", "amount": "${options.Amount}", "transid": "${options.TansactionID}", "msisdn": "${options.Msisdn}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ConfirmConnectedAppPayment','object','{ "URL": "https://172.16.100.5:4300/azam/confirm/payment", "METHOD": "POST", "JSON": true, "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', '`{ "apiPath": "${options.apiPath}", "transactionstatus": "${options.transactionstatus}", "message": "${options.message}", "operator": "${options.operator}", "reference": "${options.reference}", "utilityref": "${options.utilityref}", "amount": "${options.amount}", "transid": "${options.transid}", "msisdn": "${options.msisdn}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ConfirmAzamMediaPayment','object','{ "URL": "http://34.245.88.152:3030/api/wallet-transaction/v2/callback", "METHOD": "POST", "JSON": true }',NULL,'outgoing','active', '`{ "transactionstatus": "${options.TransactionStatus}", "message": "${options.Message}", "operator": "${options.Operator}", "reference": "${options.ReferenceID}", "utilityref": "${options.UtilityReference}", "amount": "${options.Amount}", "transid": "${options.TansactionID}", "msisdn": "${options.Msisdn}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('PayToAzamMediaPayment','object','{ "URL": "https://172.16.100.5:4300/azam/confirm/payment", "METHOD": "POST", "JSON": true, "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', '`{ "apiPath": "${options.apiPath}", "transactionstatus": "${options.transactionstatus}", "message": "${options.message}", "operator": "${options.operator}", "reference": "${options.reference}", "utilityref": "${options.utilityref}", "amount": "${options.amount}", "transid": "${options.transid}", "msisdn": "${options.msisdn}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/confirm/payment','object',NULL,NULL,'incoming','active', '`{ "operator": "string", "reference": "string", "utilityref": "string", "amount": "string", "transid": "string", "msisdn": "string" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/confirm/payment','object',NULL,NULL,'incoming','active', '`{ "operator": "string", "reference": "string", "utilityref": "string", "amount": "string", "transid": "string", "msisdn": "string" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/users','object',NULL,NULL,'incoming','active', '`{ "Username": "string", "Password": "string", "Name": "string", "Address": "string", "MobileNumber": "string", "RoleIDs": ["string"] }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/zantel/ussdPush/callback','string', '{ }', null, '`<RESPONSE> <REQUESTID>${options.REQUESTID}</REQUESTID> <REFERENCEID>${options.ReferenceID}</REFERENCEID> <TYPE>PAYMENT_RESPONSE</TYPE> <RESPONSETIME>${options.REQUESTTIME}</RESPONSETIME> <ERRORCODE>1</ERRORCODE> <ERRORDESC>Internal server error</ERRORDESC> <ADDDATA></ADDDATA> </RESPONSE>`', '`<RESPONSE><REQUESTID>${options.REQUESTID}</REQUESTID><REFERENCEID>${options.ReferenceID}</REFERENCEID><TYPE>PAYMENT_RESPONSE</TYPE><RESPONSETIME>${options.REQUESTTIME}</RESPONSETIME><ERRORCODE>0</ERRORCODE><ERRORDESC>Transaction successful</ERRORDESC><ADDDATA></ADDDATA></RESPONSE>`', 'incoming','active', '`<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <REQUEST> <REQUESTID>string</REQUESTID> <USERNAME>string</USERNAME> <PASSWORD>string</PASSWORD> <TYPE>string</TYPE> <REQUESTTIME>string</REQUESTTIME> <CUSTNAME>string</CUSTNAME> <SENDER>string</SENDER> <AMOUNT>string</AMOUNT> <ADDDATA>string</ADDDATA> <CHECKSUM>string</CHECKSUM> <PAYMENTCODE>string</PAYMENTCODE> <LANGUAGE>string</LANGUAGE> </REQUEST>`');

INSERT INTO api_configurations (`path`, `request_type`, `request_options`, `response_options`, `type`, `status`,  `request`) VALUES
('/azam/users/register', 'object', NULL, NULL, 'incoming', 'active', '`{ "email": "string", "password": "string", "fullName": "string" }`'),
('/azam/users/login', 'object', NULL, NULL, 'incoming', 'active', '`{ "email": "string", "password": "string" }`'),
('/azam/users/logout', 'object', NULL, NULL, 'incoming', 'active', '`{ }`'),


<<----------ADMIN PORTAL------------>>

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('FetchAirtelTransactions','object','{ "URL": "https://172.16.100.5:4301/azam/airtel/fetchTransactions", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchHalotelTransactions','object','{ "URL": "https://172.16.100.5:4201/azam/halotel/fetchTransactions", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchTigoTransactions','object','{ "URL": "https://172.16.100.5:4201/azam/tigo/fetchTransactions", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchVodacomTransactions','object','{ "URL": "https://172.16.100.5:4201/azam/vodacom/fetchTransactions", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchZantelTransactions','object','{ "URL": "https://172.16.100.5:4201/azam/zantel/fetchTransactions", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL);

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('FetchAirtelTransactionsCount','object','{ "URL": "https://172.16.100.5:4301/azam/airtel/fetchTransactionsCount", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchHalotelTransactionsCount','object','{ "URL": "https://172.16.100.5:4301/azam/halotel/fetchTransactionsCount", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchTigoTransactionsCount','object','{ "URL": "https://172.16.100.5:4301/azam/tigo/fetchTransactionsCount", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchVodacomTransactionsCount','object','{ "URL": "https://172.16.100.5:4301/azam/vodacom/fetchTransactionsCount", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL),
('FetchZantelTransactionsCount','object','{ "URL": "https://172.16.100.5:4301/azam/zantel/fetchTransactionsCount", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', NULL);

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/transactions/fetchTransactions', 'object', NULL, NULL, 'incoming', 'active', '`{}`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/v1/checkout', 'object', NULL, NULL, 'incoming', 'active', '`{}`');

INSERT INTO `api_configurations`( `path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('/azam/nmb/queryaccount', 'object', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'incoming', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('/azam/nmb/registermerchant', 'object', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'incoming', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations`( `path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('NmbAccountInquiry', 'object', '`{ "username": "${options.username}", "password": "${options.password}", "request": { "operation": "${options.operation}", "accountnumber": "${options.accountnumber}", "azamtransactionref": "${options.azamtransactionref}" } }`', '{ "URL": "http://196.216.218.35/AzamAdapter/AzamWS", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }', NULL, NULL, NULL, NULL, 0, 'outgoing', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('NmbMerchantRegistration', 'object', '`{ "username": "${options.username}", "password": "${options.password}", "request": { "operation": "${options.request.operation}", "accountnumber": "${options.request.accountnumber}", "mechantname": "${options.request.mechantname}", "azamtime": "${options.request.azamtime}", } }`', '{ "URL": "http://196.216.218.35/AzamAdapter/AzamWS", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }', NULL, NULL, NULL, NULL, 0, 'outgoing', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('/azam/nmb/deregisterMerchant', 'object', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'incoming', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('NmbMerchantDeregistration', 'object', '`{ "username": "${options.username}", "password": "${options.password}", "request": { "operation": "${options.request.operation}", "drtoken": "${options.request.drtoken}", "azamtime": "${options.request.azamtime}" } }`', '{ "URL": "http://196.216.218.35/AzamAdapter/AzamWS", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }', NULL, NULL, NULL, NULL, 0, 'outgoing', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('/azam/nmb/initiatetransaction', 'object', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'incoming', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `api_configurations` (`path`, `request_type`, `request`, `request_options`, `response`, `error_response`, `success_response`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`) VALUES
('NmbTransactionInitiation', 'object', '`{ "username": "${options.username}", "password": "${options.password}", "request": { "operation": "${options.request.operation}", "merchantmobile": "${options.request.merchantmobile}", "drtoken": "${options.request.drtoken}", "amount": "${options.request.amount}", "businesscode": "${options.request.businesscode}", "azamtransactionref": "${options.request.azamtransactionref}" } }`', '{ "URL": "http://196.216.218.35/AzamAdapter/AzamWS", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }', NULL, NULL, NULL, NULL, 0, 'outgoing', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

<<----------------PRODUCTION--------------->>

INSERT INTO api_configurations (`path`, `request_type`, `request_options`, `response_options`, `skip_validation`, `type`, `status`, `created_at`, `updated_at`, `request`) VALUES
('CheckUserForAzamTVRequest','string','{"URL": "https://testmq.azammedia.com/TestWebServices/Service.asmx","METHOD": "POST","HEADERS": {"Content-type": "text/xml"},"QS": {"WSDL": ""}, "REJECT_UNAUTHORIZED": false, "INSECURE": false}',NULL,0,'outgoing','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><Header><ns1:MQUserNameToken><ns1:User_id>AzamPay</ns1:User_id><ns1:Password>AzamPaytest20</ns1:Password><ns1:ExternalPartyName>AzamPay</ns1:ExternalPartyName></ns1:MQUserNameToken></Header><Body><ns1:GetCustomerInfo><ns1:CustomerInfoXML><![CDATA[<REQUESTINFO><KEY_NAMEVALUE><KEY_NAME>SMARTCARD</KEY_NAME><KEY_VALUE>${options.referenceNumber.senderMsisdn}</KEY_VALUE></KEY_NAMEVALUE></REQUESTINFO>]]></ns1:CustomerInfoXML><ns1:ReferenceNo>${options.referenceNo}</ns1:ReferenceNo></ns1:GetCustomerInfo></Body></Envelope>`'),
('PaymentMqService','string','{"URL": "https://testmq.azammedia.com/TestWebServices/Service.asmx","METHOD": "POST","HEADERS": {"Content-type": "text/xml"},"QS": {"WSDL": ""}, "REJECT_UNAUTHORIZED": false, "INSECURE": false}',NULL,0,'outgoing','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '`<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"> <Header><ns1:MQUserNameToken> <ns1:User_id>AzamPay</ns1:User_id> <ns1:Password>AzamPaytest20</ns1:Password><ns1:ExternalPartyName>AzamPay</ns1:ExternalPartyName> </ns1:MQUserNameToken> </Header><Body> <ns1:MakePayment> <ns1:MakePaymentXML><![CDATA[<REQUESTINFO><KEY_NAMEVALUE><KEY_NAME>SMARTCARD</KEY_NAME><KEY_VALUE>${options.smartCardNo}</KEY_VALUE></KEY_NAMEVALUE><PAYMENTINFO><AMOUNT>${options.amount}</AMOUNT><PAYMODE>CA</PAYMODE><RECEIPTNO>${options.reciptNo}</RECEIPTNO><PAYMENTDATE>${options.paymentDate}</PAYMENTDATE><OPENITEM>DEFAULT</OPENITEM><REMARKS>${options.remarks}</REMARKS></PAYMENTINFO></REQUESTINFO>]]></ns1:MakePaymentXML> <ns1:ReferenceNo>${options.referenceNo}</ns1:ReferenceNo> </ns1:MakePayment></Body></Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ConfirmSarafuPayment','object','{ "URL": "https://172.18.5.7:4000/confirmPayment", "METHOD": "POST", "REJECT_UNAUTHORIZED": false, "JSON": true }',NULL,'outgoing','active', '`{ "transactionstatus": "${options.TransactionStatus}", "message": "${options.Message}", "operator": "${options.Operator}", "reference": "${options.ReferenceID}", "utilityref": "${options.UtilityReference}", "amount": "${options.Amount}", "transid": "${options.TansactionID}", "msisdn": "${options.Msisdn}" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ConfirmConnectedAppPayment','object','{ "URL": "https://172.16.111.5:8080/azam/confirm/payment", "METHOD": "POST", "JSON": true, "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', '`{ "apiPath": "${options.apiPath}", "transactionstatus": "${options.transactionstatus}", "message": "${options.message}", "operator": "${options.operator}", "reference": "${options.reference}", "utilityref": "${options.utilityref}", "amount": "${options.amount}", "transid": "${options.transid}", "msisdn": "${options.msisdn}" }`');

HALOTEL:

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/normal/ussd/C2B','string',NULL, '{"replacement_fields": {"soapenv:": "","int:": ""}}', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>${options.msg}</message><refid>${options.reference_id}</refid><response_time>${options.response_time}</response_time><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>${options.msg}</message><refid>${options.reference_id}</refid><response_time>${options.response_time}</response_time><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`','incoming','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://service.com/"><soapenv:Header /><soapenv:Body><int:HaloPesaServiceAPI><requestid>154329405</requestid><username>xxx</username><password>xxx</password><request_time>20180601092349</request_time><amount>1000</amount><sender_msisdn>255623333666</sender_msisdn><sender_name>NGUYEN HUU HANH</sender_name><referenceid>66952</referenceid><business_no></business_no><addition_data></addition_data><check_sum>b875460229adc88cef4bd9904b0b06748e2b2b10eb560078a7f0ace2ba4b2cb4</check_sum></int:HaloPesaServiceAPI></soapenv:Body></soapenv:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/ussdpush/initiatepayment','object',NULL,NULL, null, null,'incoming','active', '`{ "PartnerCode": "string", "SenderMsisdn": "string", "ReferenceMsisdn": "string" }`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/ussdpush/updatepayment','string', '{ "replacement_fields": { "referenceid": "ReferenceID", "S:": "", "ns2:": "" } }', null, '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>Internal server error</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>Payment received</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', 'incoming','active', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>string</message><referenceid>string</referenceid><response_time>string</response_time><response_type>string</response_type><addition_data>string</addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/halotel/ussdpush/callback','string', '{ "replacement_fields": { "referenceid": "ReferenceID", "S:": "", "ns2:": "" } }', null, '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>9012</response_code><message>Internal server error</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>Payment received</message><referenceid>${options.ReferenceID}</referenceid><response_time>${options.ResponseTime}</response_time><response_type>ACK</response_type><addition_data></addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`', 'incoming','active', '`<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:HaloPesaServiceAPIResponse xmlns:ns2="http://service.com/"><return><response_code>0</response_code><message>string</message><referenceid>string</referenceid><response_time>string</response_time><response_type>string</response_type><addition_data>string</addition_data></return></ns2:HaloPesaServiceAPIResponse></S:Body></S:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`, `error_response`, `success_response`,`type`,`status`, `request`) VALUES
('PayHalotelInstance','string','{ "URL": "http://10.225.198.105:8020/ServiceAPI", "METHOD": "POST", "HEADERS": { "Content-type": "text/xml", "Accept": "*/*", "Accept-Encoding": "gzip, deflate" } }', null, null, null,'outgoing','active', '`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.merchant.vmoney.viettel.com/"> <soapenv:Header /> <soapenv:Body> <ws:HaloPesaServiceAPI> <request> <requestid>${options.requestid}</requestid> <username>${options.username}</username> <password>${options.password}</password> <request_time>${options.request_time}</request_time> <amount>${options.amount}</amount> <sender_msisdn>${options.senderMsisdn}</sender_msisdn> <beneficiary_accountid>${options.beneficiary_accountid}</beneficiary_accountid> <referenceid>${options.referenceid}</referenceid> <business_no>${options.business_no}</business_no> <function_code>${options.function_code}</function_code> <addition_data /> <check_sum>${options.check_sum}</check_sum> </request> </ws:HaloPesaServiceAPI> </soapenv:Body></soapenv:Envelope>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('HalotelUssdPush','object','{ "URL": "https://172.16.111.5:4201/azam/halotel/ussdpush/initiatepayment", "METHOD": "POST", "REJECT_UNAUTHORIZED": false }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "SenderMsisdn": "${options.SenderMsisdn}", "ReferenceMsisdn": "${options.ReferenceMsisdn}", "Amount": "${options.Amount}" }`');

AIRTEL:

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/airtel/ussdnormal','string','{"replacement_fields": {"COMMAND": "RequestToken", "transID": "TransID", "amount": "Amount", "referenceField": "ReferenceField", "MSISDN": "Msisdn", "paybillnumber": "utilitycode"}}',NULL,'incoming','active', '`<COMMAND><APIusername>string</APIusername><APIPassword>string</APIPassword><transID>string</transID><amount>string</amount><paybillnumber>string</paybillnumber><referenceField>string</referenceField><MSISDN>string</MSISDN></COMMAND>`'),
('/azam/airtel/ussdpush','object','',NULL,'incoming','active', '{"PartnerCode": "string", "CustomerMsisdn": "string", "Amount": "string", "ReferenceMsisdn": "string"}');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/airtel/ussdpush/callback','string','{"replacement_fields": {"COMMAND": "Command","EXTTRID": "ExternalReferenceID"}}',NULL,'incoming','active', '`<COMMAND><TYPE>CALLBCKREQ</TYPE><serviceType>CALLBCKREQ</serviceType><interfaceId>ONLINEPAY_{3ppname}</interfaceId><TXNSTATUS>200</TXNSTATUS><TXNID>MP180907.1925.B00001</TXNID><MESSAGE>success</MESSAGE><EXTTRID>1807111203222</EXTTRID><REFERENCE>null</REFERENCE><INTERFACEID>ONLINEPAY_{3ppname}</INTERFACEID></COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('AirtelCallbackApi', 'string', '{ "URL": "http://172.27.34.81:10066/?LOGIN=PushAPI&PASSWORD=MPtc1ToayCkCMZZeHUu0snA3a&REQUEST_GATEWAY_CODE=THIRDPARTY&REQUEST_GATEWAY_TYPE=USSD", "METHOD": "POST", "HEADERS": { "Content-type": "application/xml" }, "REJECT_UNAUTHORIZED": false }', null, null, 'outgoing', 'active', '`<COMMAND><TYPE>PUSHPIN</TYPE><MSISDN>${options.CustomerMsisdn}</MSISDN><MSISDN2>${options.MSISDN2}</MSISDN2><AMOUNT>${options.Amount}</AMOUNT><INTERFACEID>ONLINEPAY_${options.InterfaceName}</INTERFACEID><REFERENCE_NO>${options.ReferenceID}</REFERENCE_NO><EXT_TRID>${options.ExternalReferenceID}</EXT_TRID></COMMAND>`');
INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('AirtelUssdPush','object','{ "URL": "https://172.16.111.5:4301/azam/airtel/ussdpush", "METHOD": "POST", "REJECT_UNAUTHORIZED": false, "AGENT_OPTIONS": { "securityOptions": "TLSv1_method", "CERT": "/home/atharv/Airtel.crt", "PASS_PHRASE": "PUSH_API@123" } }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "CustomerMsisdn": "${options.CustomerMsisdn}", "ReferenceMsisdn": "${options.ReferenceMsisdn}", "Amount": "${options.Amount}" }`');

TIGO:

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('/azam/tigo/validatetoken','object','{}',NULL,'incoming','active', '`{"Username": "string", "Password": "string"}`'),
('/azam/tigo/initiatetransaction','object','{}',NULL,'incoming','active', '`{"CustomerMSISDN": "string", "ReferenceMSISDN": "string", "Amount": "string"}`'),
('/azam/tigo/querytransaction','object','{}',NULL,'incoming','active', '`{"ReferenceID": "string"}`'),
('ValidateTigoToken','form','{ "URL": "http://accessgw.tigo.co.tz:8080/SARAFU2DMGetToken", "METHOD": "POST", "HEADERS": { "Content-type": "application/x-www-form-urlencoded" } }',NULL,'outgoing','active', '`{"username": "${options.Username}", "password": "${options.Password}", "grant_type": "password"}`'),
('QueryTigoTransaction','object','{ "URL": "https://10.222.130.104:9101/API/Heartbeat/Heartbeat", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"ReferenceID": "${options.ReferenceID}"}`'),
('InitiateTigoTransaction','object','{ "URL": "http://accessgw.tigo.co.tz:8080/SARAFU2DMPushBillPay", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"CustomerMSISDN": "${options.CustomerMSISDN}", "BillerMSISDN": "${options.BillerMSISDN}", "Amount": "${options.Amount}", "Remarks": "${options.Remarks}", "ReferenceID": "${options.ReferenceID}"}`'),
('PayTigoBillInSync','string','{ "URL": "https://10.222.130.104:9101/API/Heartbeat/Heartbeat", "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`<?xml version="1.0"?><COMMAND><TYPE>string</TYPE><TXNID>string</TXNID><MSISDN>string</MSISDN><AMOUNT>string</AMOUNT><COMPANYNAME>string</COMPANYNAME><CUSTOMERREFERENCEID>string</CUSTOMERREFERENCEID></COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/tigo/ussdpush/callback','object',NULL,'`{"ResponseCode": "BILLER-18-3020-E", "ResponseStatus": false, "ResponseDescription": "Callback failed", "ReferenceID": "${options.ReferenceID}", "statusCode": 500}`', '`{"ResponseCode": "BILLER-18-0000-S", "ResponseStatus": true, "ResponseDescription": "Callback successful", "ReferenceID": "${options.ReferenceID}", "statusCode": 200}`','incoming','active', '`{"Description": "string", "ReferenceID": "string", "Amount": "string"}`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/azam/tigo/ussd/normalC2B','string',NULL,'`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <txnID>${options.txnID}</txnID> <refID>${options.refID}</refID> <result>${options.result}</result> <errorCode>${options.errorCode}</errorCode> <msisdn>${options.msisdn}</msisdn> <flag>${options.flag}</flag> <content>${options.content}</content> </COMMAND>`', '`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <txnID>${options.txnID}</txnID> <refID>${options.refID}</refID> <result>${options.result}</result> <errorCode>${options.errorCode}</errorCode> <msisdn>${options.msisdn}</msisdn> <flag>${options.flag}</flag> <content>${options.content}</content> </COMMAND>`','incoming','active', '`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <TYPE>string</TYPE> <TXNID>string</TXNID> <MSISDN>string</MSISDN> <AMOUNT>string</AMOUNT> <COMPANYNAME>string</COMPANYNAME> <CUSTOMERREFERENCEID>string</CUSTOMERREFERENCEID> </COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`error_response`, `success_response`,`type`,`status`, `request`) VALUES
('/tigo/ussd/normalC2B','string',NULL,'`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <txnID>${options.txnID}</txnID> <refID>${options.refID}</refID> <result>${options.result}</result> <errorCode>${options.errorCode}</errorCode> <msisdn>${options.msisdn}</msisdn> <flag>${options.flag}</flag> <content>${options.content}</content> </COMMAND>`', '`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <txnID>${options.txnID}</txnID> <refID>${options.refID}</refID> <result>${options.result}</result> <errorCode>${options.errorCode}</errorCode> <msisdn>${options.msisdn}</msisdn> <flag>${options.flag}</flag> <content>${options.content}</content> </COMMAND>`','incoming','active', '`<?xml version="1.0" encoding="UTF-8"?> <COMMAND> <TYPE>string</TYPE> <TXNID>string</TXNID> <MSISDN>string</MSISDN> <AMOUNT>string</AMOUNT> <COMPANYNAME>string</COMPANYNAME> <CUSTOMERREFERENCEID>string</CUSTOMERREFERENCEID> </COMMAND>`');

INSERT INTO api_configurations (`path`,`request_type`,`request_options`,`response_options`,`type`,`status`, `request`) VALUES
('ValidateTigoTokenInternal','object','{ "URL": "https://172.16.111.5:4101/azam/tigo/validatetoken", "REJECT_UNAUTHORIZED": false, "METHOD": "POST", "HEADERS": { "Content-type": "application/json" } }',NULL,'outgoing','active', '`{"Username": "${options.Username}", "Password": "${options.Password}"}`'),
('InitiateTigoTransactionInternal','object','{ "URL": "https://172.16.111.5:4101/azam/tigo/initiatetransaction", "REJECT_UNAUTHORIZED": false, "METHOD": "POST" }',NULL,'outgoing','active', '`{ "PartnerCode": "${options.PartnerCode}", "CustomerMSISDN": "${options.CustomerMSISDN}", "ReferenceMSISDN": "${options.ReferenceMSISDN}", "Amount": "${options.Amount}" }`');
